service: user-center

env: development

server:
  protocol: http
  host: "0.0.0.0"
  port: 8888
  mode: debug

mongo:
  database: user-center
  url: mongodb://docker:mongopw@localhost:55002


mysql:
  dsn: mysql://root:mysqlpw@mysql-OKcB:3306
  host: 127.0.0.1 #host.docker.internal
  port: 33060
  user: root
  password: mysqlpw
  database: yichat
  charset: utf8mb4
  timeZone: Local
  parseTime: true
  logLevel: debug
  slowSql: 50ms

redis:
  address: 127.0.0.1:55000
  username: default
  password: redispw
  db: 0
